# Generated by Django 2.1.15 on 2021-06-10 09:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(verbose_name='購買數量')),
                ('customer_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='客戶ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'order ',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_pcs', models.IntegerField(verbose_name='商品庫存數量')),
                ('price', models.IntegerField(verbose_name='商品價格')),
                ('shop_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='商品所屬館別')),
                ('vip', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'product ',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoporder.product'),
        ),
    ]
